statsFolder = "stats"
graphsFolder = "graphs"
logsFolder = "logs"
domainNamesFolder = "domainNames"
configsFolder = "configs"
chordFolderName = "chord"
hierarchicalFolderName = "hierarchical"

chord = "chord"
hierarchical = "hierarchical"